# netlify.toml - place this at the root of your repo (same level as Frontend/)

[build]
  base = "Frontend"             # Where package.json lives and commands run
  command = "npm run build"     # Vite build command
  publish = "dist"              # Serve the build output folder
  # Package directory is Frontend/ in UI; leave this in UI if required

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
